-- Dashboard amministratore "Gestione commesse"
-- Eseguire con Supabase CLI oppure incollare nel SQL Editor.

create table if not exists public.commessa_document_status (
  id bigint generated by default as identity primary key,
  cdl_id bigint,
  commessa_folder text not null unique,
  commessa_code text,
  commessa_name text not null,
  client text,
  completion_percentage integer not null default 0 check (completion_percentage between 0 and 100),
  completed_folders integer not null default 0,
  expected_folders integer not null default 11,
  total_files integer not null default 0,
  folder_status jsonb not null default '[]'::jsonb,
  scanned_at timestamptz not null default now(),
  scan_error text
);

create index if not exists idx_commessa_document_status_completion
  on public.commessa_document_status(completion_percentage);
create index if not exists idx_commessa_document_status_code
  on public.commessa_document_status(commessa_code);
create index if not exists idx_commessa_document_status_scanned_at
  on public.commessa_document_status(scanned_at desc);

create table if not exists public.commessa_scan_requests (
  id bigint generated by default as identity primary key,
  requested_by uuid default auth.uid(),
  requested_at timestamptz not null default now(),
  status text not null default 'pending' check (status in ('pending', 'running', 'completed', 'failed')),
  processed_at timestamptz,
  error_message text
);

create index if not exists idx_commessa_scan_requests_status_requested
  on public.commessa_scan_requests(status, requested_at);

alter table public.commessa_document_status enable row level security;
alter table public.commessa_scan_requests enable row level security;

-- I risultati della scansione contengono informazioni operative: solo gli admin li vedono.
drop policy if exists commessa_document_status_admin_select on public.commessa_document_status;
create policy commessa_document_status_admin_select
on public.commessa_document_status
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.user_id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
);

-- Gli admin possono leggere lo stato delle richieste e chiederne una nuova.
drop policy if exists commessa_scan_requests_admin_select on public.commessa_scan_requests;
create policy commessa_scan_requests_admin_select
on public.commessa_scan_requests
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles p
    where p.user_id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
);

drop policy if exists commessa_scan_requests_admin_insert on public.commessa_scan_requests;
create policy commessa_scan_requests_admin_insert
on public.commessa_scan_requests
for insert
to authenticated
with check (
  requested_by = auth.uid()
  and exists (
    select 1
    from public.profiles p
    where p.user_id = auth.uid()
      and p.role = 'admin'
      and p.is_active = true
  )
);

comment on table public.commessa_document_status is
  'Stato documentale delle cartelle commessa rilevato dall agent locale sul file server.';
comment on table public.commessa_scan_requests is
  'Coda di richieste manuali di scansione avviate dalla dashboard amministratore.';
